### ISSUE TITLE
The laptop jams during ec firmware flashing procedure on NS70

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#183]
**Dasharo version**
v1.3.0, v1.4.0

**Dasharo variant**
NS70

**Affected component(s) or functionality**
EC firmware flashing

**Brief summary**
The laptop jams during ec firmware flashing procedure.

**How reproducible**
100%

**How to reproduce**

1. Go through this procedure: https://docs.dasharo.com/variants/novacustom_ns5x_7x/ec_recovery/

**Expected behavior**
Output after run flashing command:
```
cargo build --manifest-path ecflash/Cargo.toml --example isp --release
    Finished release [optimized] target(s) in 0.03s
sudo ecflash/target/release/examples/isp build/clevo/ns50mu/2022-08-17_229aaff/ec.rom
Buffer size: 128
ID: 5570 VER: 2
SPI read
Saving ROM to backup.rom
SPI sector erase 000000
SPI sector erase 000400
SPI sector erase 000800
SPI sector erase 000C00
SPI sector erase 001000
SPI sector erase 001400
SPI sector erase 001800
SPI sector erase 001C00
SPI sector erase 002000
SPI sector erase 002400
SPI sector erase 002800
SPI sector erase 002C00
SPI sector erase 003000
SPI sector erase 003400
SPI sector erase 003800
SPI sector erase 003C00
SPI sector erase 004000
SPI sector erase 004400
SPI sector erase 004800
SPI sector erase 004C00
SPI sector erase 005000
SPI sector erase 005400
SPI sector erase 005800
SPI sector erase 005C00
SPI sector erase 006000
SPI sector erase 006400
SPI sector erase 006800
SPI sector erase 006C00
SPI sector erase 007000
SPI sector erase 007400
SPI sector erase 007800
SPI sector erase 007C00
SPI sector erase 008000
SPI sector erase 008400
SPI sector erase 008800
SPI sector erase 008C00
SPI sector erase 009000
SPI sector erase 009400
SPI sector erase 009800
SPI sector erase 009C00
SPI sector erase 00A000
SPI sector erase 00A400
SPI sector erase 00A800
SPI sector erase 00AC00
SPI sector erase 00B000
SPI sector erase 00B400
SPI sector erase 00B800
SPI sector erase 00BC00
SPI sector erase 00C000
SPI sector erase 00C400
SPI sector erase 00C800
SPI sector erase 00CC00
SPI sector erase 00D000
SPI sector erase 00D400
SPI sector erase 00D800
SPI sector erase 00DC00
SPI sector erase 00E000
SPI sector erase 00E400
SPI sector erase 00E800
SPI sector erase 00EC00
SPI sector erase 00F000
SPI sector erase 00F400
SPI sector erase 00F800
SPI sector erase 00FC00
SPI sector erase 010000
SPI sector erase 010400
SPI sector erase 010800
SPI sector erase 010C00
SPI sector erase 011000
SPI sector erase 011400
SPI sector erase 011800
SPI sector erase 011C00
SPI sector erase 012000
SPI sector erase 012400
SPI sector erase 012800
SPI sector erase 012C00
SPI sector erase 013000
SPI sector erase 013400
SPI sector erase 013800
SPI sector erase 013C00
SPI sector erase 014000
SPI sector erase 014400
SPI sector erase 014800
SPI sector erase 014C00
SPI sector erase 015000
SPI sector erase 015400
SPI sector erase 015800
SPI sector erase 015C00
SPI sector erase 016000
SPI sector erase 016400
SPI sector erase 016800
SPI sector erase 016C00
SPI sector erase 017000
SPI sector erase 017400
SPI sector erase 017800
SPI sector erase 017C00
SPI sector erase 018000
SPI sector erase 018400
SPI sector erase 018800
SPI sector erase 018C00
SPI sector erase 019000
SPI sector erase 019400
SPI sector erase 019800
SPI sector erase 019C00
SPI sector erase 01A000
SPI sector erase 01A400
SPI sector erase 01A800
SPI sector erase 01AC00
SPI sector erase 01B000
SPI sector erase 01B400
SPI sector erase 01B800
SPI sector erase 01BC00
SPI sector erase 01C000
SPI sector erase 01C400
SPI sector erase 01C800
SPI sector erase 01CC00
SPI sector erase 01D000
SPI sector erase 01D400
SPI sector erase 01D800
SPI sector erase 01DC00
SPI sector erase 01E000
SPI sector erase 01E400
SPI sector erase 01E800
SPI sector erase 01EC00
SPI sector erase 01F000
SPI sector erase 01F400
SPI sector erase 01F800
SPI sector erase 01FC00
SPI read
SPI AAI word program (accelerated)
  program 35210 / 35210
SPI read
Successfully programmed SPI ROM
```

**Actual behavior**
Output after run flashing command:
```
cargo build --manifest-path ecflash/Cargo.toml --example isp --release
    Finished release [optimized] target(s) in 0.03s
sudo ecflash/target/release/examples/isp build/clevo/ns50mu/2022-08-17_229aaff/ec.rom
Buffer size: 128
ID: 5570 VER: 2
SPI read
Saving ROM to backup.rom
SPI sector erase 000000
```
And in that state it jams and doesn't go any further

**Screenshots**

**Additional context**

**Solutions you've tried**
More than 10 attempts.

**Comment by mkopec** [comment]
- Is the laptop grounded? System76 recommends a USB-C cable from the host computer to the laptop
- Did you try reseating the cable on both sides? Sometimes it needs a little push to seat properly

**Comment by Pokisiekk** [comment]
The laptop was grounded, like is described in documentation.
I was constantly changing the ends of the cable, I unplugged something and connected it again, but I do not have time to do 50 repetitions until it finally works - When there is something wrongly connected, it crashes such errors:

```
cargo build --manifest-path ecflash/Cargo.toml --example isp --release
    Finished release [optimized] target(s) in 0.01s
sudo ecflash/target/release/examples/isp build/clevo/ns50mu/2022-08-17_229aaff/ec.rom
[sudo] password for kpokornicki: 
thread 'main' panicked at 'failed to flash: Error { kind: InvalidInput, description: "received echo of 00 instead of 76" }', examples/isp.rs:840:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [src/board/system76/common/common.mk:76: flash_external] Error 101
```

or

```
cargo build --manifest-path ecflash/Cargo.toml --example isp --release
    Finished release [optimized] target(s) in 0.01s
sudo ecflash/target/release/examples/isp build/clevo/ns50mu/2022-08-17_229aaff/ec.rom
[sudo] password for kpokornicki: 
Buffer size: 128
thread 'main' panicked at 'failed to flash: Error { kind: Io(TimedOut), description: "Operation timed out" }', examples/isp.rs:840:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [src/board/system76/common/common.mk:76: flash_external] Error 101
```

so if after 5/6 attempts it finally starts the flashing procedure and jams during the process, it should not be the fault of a bad connection.

**Comment by wessel-novacustom** [comment]
I confirm this problem for a NS51PU

**Comment by wessel-novacustom** [comment]
Double grounding and 20+ attempts solves this issue. Also, the laptop's battery and CMOS battery need to be unplugged.

In some cases of broken hardware, the EC is no longer writable.

The issue can be closed.
